version: '3.7'
services:
  courses:
    image: jdvelasq/hadoop:2.8.5
    ports:
      - "50070:50070"
      - "8088:8088"
      - "8888:8888"
      - "9000:9000"      
    volumes:
      - type: bind
        source: "$PWD"
        target: /app
